import "./globals.css";
import SideNav from "@/app/ui/sidenav";
export const metadata = {
  title: "Weather",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col md:flex-row md:overflow-hidden bg-ground">
      <div className="w-full flex-none md:w-64">
        < SideNav/>
      </div>
      <div>
        {children}
      </div>
      </body>
    </html>
  );
}
